# Generated by Django 5.2.1 on 2025-06-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Unknown', max_length=100, unique=True)),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('email', models.EmailField(default='Unknown', max_length=255, unique=True)),
                ('phone', models.CharField(default='Unknown', max_length=12)),
                ('password', models.CharField(default='Unknown', max_length=255)),
                ('type', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='None', max_length=100)),
                ('specialization', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctors_description', models.CharField(default='', max_length=255)),
                ('medicines', models.CharField(default='None', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagement.credentials')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagement.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(default='None', max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagement.credentials')),
            ],
        ),
    ]
